<div class="row">
	<div class="col-lg-12">
		<h1>Popular PHP Repositories on GitHub</h1>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<h2>"<?php echo $this->project['repository_name'] ?>" Repository Details</h2>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<table id="table-main" cellpadding=10" cellspacing="10" class="table table-bordered table-striped">
			<tbody>
				<tr style="background-color: lightblue;">
					<td>Repository ID #</td>
				    <td><?php echo $this->project['repository_id'] ?></td>
				</tr>
				<tr>
					<td>Repository Name</td>
				    <td><?php echo $this->project['repository_name'] ?></td>
				</tr>
				<tr style="background-color: lightblue;">
					<td>Repository URL</td>
				    <td><?php echo $this->project['repository_url'] ?></td>
				</tr>
				<tr>
					<td>Date Created</td>
				    <td><?php echo $this->project['date_created'] ?></td>
				</tr>
				<tr style="background-color: lightblue;">
					<td>Last Updated</td>
				    <td><?php echo $this->project['last_updated'] ?></td>
				</tr>
				<tr>
					<td>Description</td>
				    <td><?php echo $this->project['description'] ?></td>
				</tr>
				<tr style="background-color: lightblue;">
				    <td>No. of Stars</td>
				    <td><?php echo $this->project['stars'] ?></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div style="margin-top: 25px;">
		<a id="button_back" href="/index/display">BACK</a><a style="margin-left: 50px;" id="button_back" href="/">HOME</a><br>
		<a href="/"><img style="width: 150px; height: 150px;" src="<?php echo $this->baseUrl().'/images/hub_logo.png' ?>" alt="GitHub"></a><br>
	</div>
</div>
