<?php if ($this->count == 0) { ?>
<div class="row">
	<div class="col-lg-12">
		<h1 style="color: red; margin-bottom: 0px;">No PHP Github projects found.</h1><br>
		<h3 style="color: red; margin-top: 0px;">Please try again with different input.</h1>
	</div>
</div>
<?php } else { ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.js"></script>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/pagination.css'); ?> 
<div class="row">
	<div class="col-lg-12">
		<h1>PHP Github Projects</h1>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<table id="table-main" cellpadding="5" cellspacing="5" class="table table-bordered table-striped">
			<thead>
				<tr id="row-head" style="background-color: lightblue;">
				    <th>Repository ID #</th>
				    <th>Repository Name</th>
				    <th>Stars</th>
				    <th></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->projects as $project) : 
				$i = 0;
				if ($i%2 == 0) { ?>
				<tr>
				<?php } else { ?>
				<tr style="background-color: lightblue;">
				<?php } ?>
				    <td><?php echo $this->escape($project->repository_id);?></td>
				    <td><?php echo $this->escape($project->repository_name);?></td>
				    <td><?php echo $this->escape($project->stars);?></td>
				    <td class="view_button"><a id="button_view" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'displayitem', 'id'=>$project->repository_id));?>">View</a>
				    </td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
	    $('#table-main').DataTable( {
	        "order": [[ 2, "desc" ]]
	    });
	});
</script>
<?php } ?>
<div id="bottom_area">
	<a href="/"><img style="width: 150px; height: 150px;" src="<?php echo $this->baseUrl().'/images/hub_logo.png' ?>" alt="GitHub"></a><br>
	<a id="home_link" href="/">HOME</a>
</div>