<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/form_style.css'); ?> 
<div>
	<div>
		<img style="width: 175px; height: 175px;" src="<?php echo $this->baseUrl().'images/hub_logo.png' ?>" alt="GitHub">
		<h1 style="color: black;">PHP Github Projects</h1>
	</div>
</div>
<div>
	<div>
		<div>
			<?php echo $this->form ?>
		</div>
	</div>
</div>
<div style="margin-top: 25px;">
	<a id="button_back" href="/index/display">VIEW EXISTING DATA</a>
</div>